### ISSUE TITLE
Close pop up when clicking anywhere or make it not be main focus

### ISSUE THREAD

**Issue by DavidAlcns** [redSol/PoeTradeSearchEN#21] opened 2020-01-11 15:51 UTC
Any way to make it close/not focus whenever i have the pop up opened and i click e.g path of exile?

Thanks.

**Comment by JusKillmeQik** [comment] 2020-01-11 21:21
You can press ESC to close it pretty easily. I like that it stays open so I can finish trades or do something else in game without losing the price check I was doing. Maybe it's just a preference but it feels pretty out of the way and easy to move for me while staying in the foreground.

**Comment by redSol** [comment] 2020-01-11 21:47
I can add an option in config for this if you would like

**Comment by DavidAlcns** [comment] 2020-01-11 21:50
That would be awesome if it doesnt take you much time to develop

**Comment by redSol** [comment] 2020-01-12 00:26
added an option for it

**Closed as completed by redSol** 2020-01-12 00:26 UTC

**Comment by Helban** [comment] 2020-01-12 09:59
which option is it? can't see it

**Comment by DavidAlcns** [comment] 2020-01-12 10:16
@kramarz89 
    "always_on_top": true
either change it to true/false

**Comment by Helban** [comment] 2020-01-12 10:17
In that case it doesn't work as intended, once being false, if you have game focused, it wont ever come on top, causes it to feel like macro is not working

**Comment by DavidAlcns** [comment] 2020-01-12 10:24
Gonna open a bug
